// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transfer.proto
// Protobuf C++ Version: 6.33.4

#include "transfer.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr TransferResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        chunk_index_{0},
        success_{false} {}

template <typename>
PROTOBUF_CONSTEXPR TransferResponse::TransferResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TransferResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TransferResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransferResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransferResponseDefaultTypeInternal() {}
  union {
    TransferResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransferResponseDefaultTypeInternal _TransferResponse_default_instance_;

inline constexpr FileChunk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        total_size_{::int64_t{0}},
        chunk_index_{0},
        total_chunks_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileChunk::FileChunk(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(FileChunk_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileChunkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileChunkDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileChunkDefaultTypeInternal() {}
  union {
    FileChunk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileChunkDefaultTypeInternal _FileChunk_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_transfer_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_transfer_2eproto = nullptr;
const ::uint32_t
    TableStruct_transfer_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::FileChunk, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::FileChunk, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::FileChunk, _impl_.total_size_),
        PROTOBUF_FIELD_OFFSET(::FileChunk, _impl_.chunk_index_),
        PROTOBUF_FIELD_OFFSET(::FileChunk, _impl_.total_chunks_),
        PROTOBUF_FIELD_OFFSET(::FileChunk, _impl_.data_),
        0,
        2,
        3,
        4,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::TransferResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::TransferResponse, _impl_.chunk_index_),
        PROTOBUF_FIELD_OFFSET(::TransferResponse, _impl_.success_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::FileChunk)},
        {13, sizeof(::TransferResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_FileChunk_default_instance_._instance,
    &::_TransferResponse_default_instance_._instance,
};
const char descriptor_table_protodef_transfer_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016transfer.proto\"j\n\tFileChunk\022\020\n\010filenam"
    "e\030\001 \001(\t\022\022\n\ntotal_size\030\002 \001(\003\022\023\n\013chunk_ind"
    "ex\030\003 \001(\005\022\024\n\014total_chunks\030\004 \001(\005\022\014\n\004data\030\005"
    " \001(\014\"8\n\020TransferResponse\022\023\n\013chunk_index\030"
    "\001 \001(\005\022\017\n\007success\030\002 \001(\010b\006proto3"
};
static ::absl::once_flag descriptor_table_transfer_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_transfer_2eproto = {
    false,
    false,
    190,
    descriptor_table_protodef_transfer_2eproto,
    "transfer.proto",
    &descriptor_table_transfer_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_transfer_2eproto::offsets,
    file_level_enum_descriptors_transfer_2eproto,
    file_level_service_descriptors_transfer_2eproto,
};
// ===================================================================

class FileChunk::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FileChunk>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FileChunk, _impl_._has_bits_);
};

FileChunk::FileChunk(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileChunk_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FileChunk)
}
PROTOBUF_NDEBUG_INLINE FileChunk::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::FileChunk& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        filename_(arena, from.filename_),
        data_(arena, from.data_) {}

FileChunk::FileChunk(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FileChunk& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileChunk_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileChunk* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, total_size_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, total_size_),
           offsetof(Impl_, total_chunks_) -
               offsetof(Impl_, total_size_) +
               sizeof(Impl_::total_chunks_));

  // @@protoc_insertion_point(copy_constructor:FileChunk)
}
PROTOBUF_NDEBUG_INLINE FileChunk::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        filename_(arena),
        data_(arena) {}

inline void FileChunk::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, total_size_),
           0,
           offsetof(Impl_, total_chunks_) -
               offsetof(Impl_, total_size_) +
               sizeof(Impl_::total_chunks_));
}
FileChunk::~FileChunk() {
  // @@protoc_insertion_point(destructor:FileChunk)
  SharedDtor(*this);
}
inline void FileChunk::SharedDtor(MessageLite& self) {
  FileChunk& this_ = static_cast<FileChunk&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FileChunk::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FileChunk(arena);
}
constexpr auto FileChunk::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FileChunk),
                                            alignof(FileChunk));
}
constexpr auto FileChunk::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FileChunk_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FileChunk::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FileChunk>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FileChunk::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FileChunk>(), &FileChunk::ByteSizeLong,
              &FileChunk::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FileChunk, _impl_._cached_size_),
          false,
      },
      &FileChunk::kDescriptorMethods,
      &descriptor_table_transfer_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FileChunk_class_data_ =
        FileChunk::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FileChunk::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FileChunk_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FileChunk_class_data_.tc_table);
  return FileChunk_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 26, 2>
FileChunk::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FileChunk, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    FileChunk_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FileChunk>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.filename_)}},
    // int64 total_size = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileChunk, _impl_.total_size_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.total_size_)}},
    // int32 chunk_index = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileChunk, _impl_.chunk_index_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.chunk_index_)}},
    // int32 total_chunks = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileChunk, _impl_.total_chunks_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.total_chunks_)}},
    // bytes data = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 1, 0,
      PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.data_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.filename_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 total_size = 2;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.total_size_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int32 chunk_index = 3;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.chunk_index_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 total_chunks = 4;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.total_chunks_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bytes data = 5;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.data_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\11\10\0\0\0\0\0\0"
    "FileChunk"
    "filename"
  }},
};
PROTOBUF_NOINLINE void FileChunk::Clear() {
// @@protoc_insertion_point(message_clear_start:FileChunk)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.filename_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001cU)) {
    ::memset(&_impl_.total_size_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.total_chunks_) -
        reinterpret_cast<char*>(&_impl_.total_size_)) + sizeof(_impl_.total_chunks_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FileChunk::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FileChunk& this_ = static_cast<const FileChunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FileChunk::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FileChunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:FileChunk)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string filename = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_filename().empty()) {
      const ::std::string& _s = this_._internal_filename();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileChunk.filename");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int64 total_size = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_total_size() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_total_size(), target);
    }
  }

  // int32 chunk_index = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_chunk_index() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_chunk_index(), target);
    }
  }

  // int32 total_chunks = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_total_chunks() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_total_chunks(), target);
    }
  }

  // bytes data = 5;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      target = stream->WriteBytesMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FileChunk)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FileChunk::ByteSizeLong(const MessageLite& base) {
  const FileChunk& this_ = static_cast<const FileChunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FileChunk::ByteSizeLong() const {
  const FileChunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:FileChunk)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string filename = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_filename().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_filename());
      }
    }
    // bytes data = 5;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_data());
      }
    }
    // int64 total_size = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_total_size() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_total_size());
      }
    }
    // int32 chunk_index = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_chunk_index() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_chunk_index());
      }
    }
    // int32 total_chunks = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_total_chunks() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_total_chunks());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FileChunk::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<FileChunk*>(&to_msg);
  auto& from = static_cast<const FileChunk&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:FileChunk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_filename().empty()) {
        _this->_internal_set_filename(from._internal_filename());
      } else {
        if (_this->_impl_.filename_.IsDefault()) {
          _this->_internal_set_filename("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_total_size() != 0) {
        _this->_impl_.total_size_ = from._impl_.total_size_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_chunk_index() != 0) {
        _this->_impl_.chunk_index_ = from._impl_.chunk_index_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_total_chunks() != 0) {
        _this->_impl_.total_chunks_ = from._impl_.total_chunks_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FileChunk::CopyFrom(const FileChunk& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:FileChunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileChunk::InternalSwap(FileChunk* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.total_chunks_)
      + sizeof(FileChunk::_impl_.total_chunks_)
      - PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.total_size_)>(
          reinterpret_cast<char*>(&_impl_.total_size_),
          reinterpret_cast<char*>(&other->_impl_.total_size_));
}

::google::protobuf::Metadata FileChunk::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TransferResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TransferResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TransferResponse, _impl_._has_bits_);
};

TransferResponse::TransferResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TransferResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TransferResponse)
}
TransferResponse::TransferResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TransferResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TransferResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE TransferResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void TransferResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, chunk_index_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, chunk_index_) +
               sizeof(Impl_::success_));
}
TransferResponse::~TransferResponse() {
  // @@protoc_insertion_point(destructor:TransferResponse)
  SharedDtor(*this);
}
inline void TransferResponse::SharedDtor(MessageLite& self) {
  TransferResponse& this_ = static_cast<TransferResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TransferResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TransferResponse(arena);
}
constexpr auto TransferResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TransferResponse),
                                            alignof(TransferResponse));
}
constexpr auto TransferResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TransferResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TransferResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TransferResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TransferResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TransferResponse>(), &TransferResponse::ByteSizeLong,
              &TransferResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TransferResponse, _impl_._cached_size_),
          false,
      },
      &TransferResponse::kDescriptorMethods,
      &descriptor_table_transfer_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TransferResponse_class_data_ =
        TransferResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TransferResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TransferResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TransferResponse_class_data_.tc_table);
  return TransferResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
TransferResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TransferResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TransferResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TransferResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TransferResponse, _impl_.success_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(TransferResponse, _impl_.success_)}},
    // int32 chunk_index = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TransferResponse, _impl_.chunk_index_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(TransferResponse, _impl_.chunk_index_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 chunk_index = 1;
    {PROTOBUF_FIELD_OFFSET(TransferResponse, _impl_.chunk_index_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bool success = 2;
    {PROTOBUF_FIELD_OFFSET(TransferResponse, _impl_.success_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void TransferResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:TransferResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.chunk_index_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.success_) -
        reinterpret_cast<char*>(&_impl_.chunk_index_)) + sizeof(_impl_.success_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TransferResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TransferResponse& this_ = static_cast<const TransferResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TransferResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TransferResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:TransferResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 chunk_index = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_chunk_index() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_chunk_index(), target);
    }
  }

  // bool success = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_success() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_success(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TransferResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TransferResponse::ByteSizeLong(const MessageLite& base) {
  const TransferResponse& this_ = static_cast<const TransferResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TransferResponse::ByteSizeLong() const {
  const TransferResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:TransferResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // int32 chunk_index = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_chunk_index() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_chunk_index());
      }
    }
    // bool success = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_success() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TransferResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TransferResponse*>(&to_msg);
  auto& from = static_cast<const TransferResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:TransferResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_chunk_index() != 0) {
        _this->_impl_.chunk_index_ = from._impl_.chunk_index_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_success() != 0) {
        _this->_impl_.success_ = from._impl_.success_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TransferResponse::CopyFrom(const TransferResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:TransferResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TransferResponse::InternalSwap(TransferResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TransferResponse, _impl_.success_)
      + sizeof(TransferResponse::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(TransferResponse, _impl_.chunk_index_)>(
          reinterpret_cast<char*>(&_impl_.chunk_index_),
          reinterpret_cast<char*>(&other->_impl_.chunk_index_));
}

::google::protobuf::Metadata TransferResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_transfer_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
